### ISSUE TITLE
Image shows only black outline

### ISSUE THREAD

**Issue by Z0t** [tdicola/creepyportrait#1]
I followed the steps from: http://learn.adafruit.com/creepy-face-tracking-portrait?view=all 

Just compiled on recent a Raspberry Pi, wheezy (9/25), and the black outline of the face prints, but the while overlay never shows.  The video appears, and it finds my face (eventually).  This did for all 3 images.

I did not see any errors from the install script, but I did not look either.

From X:

[warning] ofAppEGLWindow: init(): X11 not availble on RPI yet, using a native window instead
[ error ] ofShader: begin(): couldn't begin, shader not loaded
[ error ] ofShader: begin(): couldn't begin, shader not loaded
[ error ] ofShader: begin(): couldn't begin, shader not loaded
[ error ] ofShader: begin(): couldn't begin, shader not loaded
[warning] ofShader: GL_VERTEX_SHADER shader reports: Compiled
[warning] ofShader: GL_FRAGMENT_SHADER shader reports: Compiled
[warning] ofShader: GL_VERTEX_SHADER shader reports: Compiled
[warning] ofShader: GL_FRAGMENT_SHADER shader reports: Compiled
libv4l2: warning v4l2 mmap buffers still mapped on close()

and I ran it from a native command line (CTRl-ALT F2):

Creepy Portrait v1.0
Copyright 2013 Tony DiCola (tony@tonydicola.com)
Homepage: https://github.com/tdicola/creepyportrait

[ error ] ofShader: begin(): couldn't begin, shader not loaded
[ error ] ofShader: begin(): couldn't begin, shader not loaded
[ error ] ofShader: begin(): couldn't begin, shader not loaded
[ error ] ofShader: begin(): couldn't begin, shader not loaded
[warning] ofShader: GL_VERTEX_SHADER shader reports: Compiled
[warning] ofShader: GL_FRAGMENT_SHADER shader reports: Compiled
[warning] ofShader: GL_VERTEX_SHADER shader reports: Compiled
[warning] ofShader: GL_FRAGMENT_SHADER shader reports: Compiled

**Comment by tdicola** [comment]
Thanks for checking out the project--I've heard from a couple people that ran into the same issue (no texture rendering on the pi), and it looks like the problem is with the split of memory between the GPU and CPU.  Can you use the raspi-config command (info here http://www.dummies.com/how-to/content/how-to-use-raspiconfig-to-set-up-your-raspberry-pi.html ) to check how much memory the GPU has, and set it to 128 MB if it's not already?

**Comment by Z0t** [comment]
It was set to 64, when I upped it to 128, the skull appeared!  Now how good is the face recognition at the sides of faces.  This seems like a good thing for my office window facing into the hall...

**Comment by tdicola** [comment]
Awesome, I'm glad that fixed the problem.  I just updated the guide to call out that you might need to make this memory split update before running.  Thanks for raising the issue!
